Updated with the latest changes (#15)
GoogleCloudPlatform/nl2sql pull request #16
Opened 2024-05-24 19:44 UTC by vagrantism

2024-05-25 10:17 UTC, solidate commented on nl2sql/datasets/base.py
What's the benefit of new changes over previous implementation of table descriptor implementation? @vagrantism

2024-05-25 10:18 UTC, solidate requested changes
Remove the .vscode folder

2024-05-25 10:33 UTC, vagrantism commented on nl2sql/datasets/base.py
Generating descriptions post-hoc ensures any filtered-out column is also removed from the descriptions. Earlier, doing this pre-hoc resulted in a bug where column filtering would have no effect on the descriptions. @tanyarw is the original author of this fix.

2024-05-25 10:36 UTC, vagrantism commented
> Remove the .vscode folder

@solidate The .vscode folder contains some basic (but important) linting configs that we would want our contributors to follow.

2024-05-25 10:41 UTC, solidate commented
> > Remove the .vscode folder
> 
> @solidate The .vscode folder contains some basic (but important) linting configs that we would want our contributors to follow.

All contributor not necessarily use vscode. The lint guide should be part of CONTRIBUTING.md
WDYT @vagrantism

2024-05-25 10:55 UTC, vagrantism commented
> > > Remove the .vscode folder
> > 
> > 
> > @solidate The .vscode folder contains some basic (but important) linting configs that we would want our contributors to follow.
> 
> All contributor not necessarily use vscode. The lint guide should be part of CONTRIBUTING.md WDYT @vagrantism

Done, PTAL

2024-05-25 11:08 UTC, solidate approved these changes
LGTM

2024-05-26 06:50 UTC, tanyarw approved these changes
LGTM

2024-05-26 09:07 UTC, merged